// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"database/sql"
)

type User struct {
	ID        int64
	Name      string
	Password  sql.NullString
	Phone     sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
